logs:
    image: busybox
    volumes:
        - /data/logs:/logs:rw
data:
    image: busybox
app:
    build: .
    dockerfile: Dockerfile_app
    ports:
        - "3000:3000"
    volumes_from:
        - logs

